### Site info:
title: Muhammed Abuali
tagline: my personal site, muhammedabuali  [ work in progress ]
author: Muhammedabuali
email: muhammedabuali@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Muhammedabuali, blog, site, Resume"
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog/
url: "http://Muhammedabuali.github.io" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: muhammedabuali
github_username:  muhammedabuali
disqus_shortname: muhammedabuali
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Muhammed Hassan. A software developer from Egypt. this is my develpment blog. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: muhammedabuali
      href: http://Muhammedabuali.github.io
      title: A developer's blog
    - name: author's website
      href: http://Muhammedabuali.github.io
      title: Muhammed Hassan's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
